name = "Neshan Kandel"
print (name[:3])
print (name[0:])
print (name[0:5:2])
print (name.endswith("an"))
print (name.startswith("Ne"))
print (name.capitalize())
print (name.upper())
print (name.replace("Kandel","Sherestha"))
print (name.split())
print (name.zfill(28))